//This is a model table to be used

// Product is individual products
//Say Mobile is a Category and iPhone 14 , Samsung Galaxy Fold 3 are Products

const mongoose = require("mongoose"); //This is to connect to mongodb
const { ObjectId } = mongoose.Schema; //This Is to import the object id of other schema.
//_id is the object id generated by category
// This is done via the following code
// category: {
//     type: ObjectID,
//     required: true, //No Empty Allowed
//     ref: "Category", //This Will Link it to The Model named Category as created in export.default Category in Category.js
//   },
const productSchema = new mongoose.Schema(
  {
    //The Structure of Table is Called Schema.
    //Model = Table
    //Here, categorySchema is our Created Schema Name where the STRUCTURE OF MONGGOSE SHOULD BE LIKE:-
    category: {
      type: ObjectId,
      required: true, //No Empty Allowed
      ref: "Category", //This Will Link it to The Model named Category as created in export.default Category in Category.js
      //This Category is The Model
    },
    product_name: {
      type: String,
      required: true, //No Empty Allowed
      trim: true, //Will Cut Any SPACE Input Whether In Front or Back BUT NOT IN THE MIDDLE
    },
    product_price: {
      type: Number,
      required: true, //No Empty Allowed
    },
    product_description: {
      type: String,
      required: true, //No Empty Allowed
    },
    product_image: {
      type: String,
      required: true, //No Empty Allowed
    },
    Count_In_Stock: {
      type: Number,
      required: true, //No Empty Allowed
      trim: true, //Will Cut Any SPACE Input Whether In Front or Back BUT NOT IN THE MIDDLE
    },
    Rating: {
      type: Number,
      default: 1, //Lowest Rating possible is one
      max: 5, //Maximum possible rating is five
    },
    review: {
      type: String,
    },
  },
  { timestamps: true }
);

//Here, Timestamps will give
// createdAt and UpdatedAt
module.exports = mongoose.model("Product", productSchema);
//Here, 'Category' is our defined Object which contains the schema is categorySchema
//This is our model name

// module.exports is like export default in react
